
# Mesh generated by MFEM simulation and mesh onto which to interpolate new simulation.
ORIGINAL_MESH=data/square.mesh
NEW_MESH=square.msh

# Solution file generated by MFEM simulation.
ORIGINAL_SOL=data/sol_J.gf

# Finite element space of variable in solution and the space to convert to.
# 0 - H1 - Lagrange elements, 
# 1 - L2, 
# 2 - H(div) - Raviart-Thomas, 
# 3 - H(curl) - Nedelec
ORIGINAL_SPACE=2
NEW_SPACE=0

# Refinement level for interpolated mesh.
REFINEMENT_LEVELS=2

./../miniapps/gslib/field-interp -o 1 -m1 ${ORIGINAL_MESH} -s1 ${ORIGINAL_SOL} -m2 ${NEW_MESH} -fts ${ORIGINAL_SPACE} -r ${REFINEMENT_LEVELS} -ft ${NEW_SPACE}

